<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}

$_product = $block->getProduct();
$_productDescription = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getShortDescription(), 'short_description');
$_materialLabel = $_product->getResource()->getAttribute('material')->getFrontendLabel();
$_materialValue =$_product->getResource()->getAttribute('material')->getFrontend()->getValue($_product);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeBaseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @escapeNotVerified */ $required ?>>
    <div class="fieldset" tabindex="0">
        <?= $block->getChildHtml('', true) ?>
    </div>
</div>

<!--<div class="material">-->
<!--	<strong class="type"><?php echo $_materialLabel;?> :</strong>-->
<!--	<p><?php echo $_materialValue;?></p>-->
<!--</div>-->

<!--<div class="description">-->
<!--    <strong class="type"><?php echo __('Details');?> :</strong>-->
<!--	<?php echo $_productDescription; ?>-->
<!--</div>-->


<!--<div class="size-guide">-->
<!--	<p><?php echo __('not sure what your size?') ?></p>-->
<!--	<a href="<?php echo $storeBaseUrl?>size-guide" target="_blank"><?php echo __('Size Chart') ?></a>-->
<!--</div>-->
