<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>

<div class="pull-left">
	<div class="cart main actions">
		<?php if ($block->getContinueShoppingUrl()): ?>
			<a class="action continue"
			   href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
			   title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
			    <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
			</a>
		<?php endif; ?>
	</div>
</div>
<div class="pull-right">
	<?php if (!$block->hasError()): ?>
	<?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
	<ul class="checkout methods items checkout-methods-items">
	<?php foreach ($methods as $method): ?>
	    <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
	    <li class="item"><?= /* @escapeNotVerified */ $methodHtml ?></li>
	    <?php endif; ?>
	<?php endforeach; ?>
	</ul>
	<?php endif; ?>
</div>