<?php
$dataPostParam = '';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<?php if ($block->isLoggedIn()) : ?>
	<div class="top-links-menu">
		<div class="greetings">
			<span><?php echo __('Hi, ') . $customerSession->getCustomer()->getFirstname() . '!'; ?></span>
		</div>
		<div class="show-link">
			<a href="" class="show-links" onclick="return false"><i class="fa fa-caret-down" aria-hidden="true"></i></a>
			<ul class="links-user">
				<li>
					<a href="<?php echo $block->getBaseUrl()?>customer/account"><?php echo __('My Account') ?></a>
				</li>
				<li>
					<a href="<?php echo $block->getBaseUrl()?>customer/account/logout/"><?php echo __('Sign Out')?></a>
				</li>
			</ul>
		</div>
	</div>
<?php else: ?>
	<li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
	    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
	        <?= $block->escapeHtml($block->getLabel()) ?>
	    </a>
	</li>
<?php endif ?>