<?php
$customerEmail = $block->getCustomerEmail();
?>

<legend class="legend"><span><?php echo __('Confirm Payment')?></span></legend>

<form enctype="multipart/form-data" 
    action="<?php echo $block->getBaseUrl() ?>banktransferconfirmation/confirmation/submit" 
    id="confirmationForm" 
    method="post"
    data-mage-init='{"validation":{}}'>
    <div class="fieldset confirmation-form" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="form-list">
        	
        	<div class="fields row">
                <div class="col-md-6">
                    <div class="input-wrap">
                        <label for="information-title" class="information-title"><?php echo __('Bank Account Information')?></label>
                    </div>
                </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
	                <div class="input-wrap">
	                   <label for="name" class="required"><?php echo __('Name')?></label>
	                    <div class="input-box">
	                        <input name="name" id="name" title="Name" class="input-text required-entry" type="text" data-validate="{required:true}">
	                    </div>
	                </div>
	            </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
	                <div class="input-wrap">
	                	<label for="email_submitter" class="required"><?php echo __('Email')?></label>
                        <div class="input-box">
                            <input name="email_submitter" id="email_submitter" title="Email" class="input-text required-entry validate-email" type="text" data-validate="{required:false}" value="<?php /* @escapeNotVerified */ echo $customerEmail ?>">
                        </div>
	                </div>
	            </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
                    <div class="input-wrap">
                        <label for="orderid" class="required"><?php echo __('Order Number')?></label>
                        <div class="input-box">
                              <input name="orderid" id="orderid" title="orderid" placeholder="<?php echo __('e.g: 000000006')?>" class="input-text required-entry" type="text" data-validate="{required:true}">
                        </div>
                    </div>
                </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
	                <div class="input-wrap">
	                   <label for="name" class="required"><?php echo __('Bank Name')?></label>
	                    <div class="input-box">
	                        <input name="bank_name" id="bank-name" title="Bank Name" class="input-text required-entry" type="text" data-validate="{required:true}">
	                    </div>
	                </div>
	            </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
	                <div class="input-wrap">
	                   <label for="name" class="required"><?php echo __('Holder Account Number')?></label>
	                    <div class="input-box">
	                        <input name="holder_account" id="holder-account" title="Holder Account Number" class="input-text required-entry" type="text" data-validate="{required:true}">
	                    </div>
	                </div>
	            </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
                    <div class="input-wrap">
                        <label for="information-title" class="information-title"><?php echo __('Transaction Information')?></label>
                    </div>
                </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
	                <div class="input-wrap">
	                   <label for="name" class="required"><?php echo __('Transfer Amount')?></label>
	                    <div class="input-box">
	                        <input name="amount" id="amount" title="Transfer Amount" class="input-text required-entry" type="text" data-validate="{required:true}">
	                    </div>
	                </div>
	            </div>
            </div>

            <div class="fields row">
            	<div class="col-md-6">
                    <div class="input-wrap">
                        <label for="bank-recipient"><?php echo __('Bank Recipient')?></label>
                        <div class="input-box">
                            <select name="recipient" id="recipient" title="Bank Recipient" value="" class="input-text" data-validate="{required:true}">
                                <?php $bankRecipient = $block->getBanksRecipient(); ?>
                                <?php foreach($bankRecipient as $option): ?>
                                    <option><?php echo $option ?></option>
                                <?php endforeach ?>
                            </select>
                            <i class="fa fa-caret-down selectoption"></i>
                        </div>                        
                    </div>
                </div>
            </div>

            <div class="fields row">
            	<div class="col-md-6">
                    <div class="input-wrap">
                        <label for="transfer-method"><?php echo __('Transfer Method')?></label>
                        <div class="input-box">
                            <select name="method" id="method" title="Transfer Method" value="" class="input-text" data-validate="{required:true}">
                                <?php $transferMethod = $block->getTransferMethod(); ?>
                                <?php foreach($transferMethod as $option): ?>
                                    <option><?php echo $option ?></option>
                                <?php endforeach ?>
                            </select>
                            <i class="fa fa-caret-down selectoption"></i>
                        </div>                        
                    </div>
                </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
	                <div class="input-wrap">
	                   <label for="name" class="required"><?php echo __('Transfer Date')?></label>
	                    <div class="input-box">
	                        <input name="date" id="date" title="Transfer Date" class="input-text required-entry" type="date" data-validate="{required:true}">
	                    </div>
	                </div>
	            </div>
            </div>

            <div class="fields row">
                <div class="col-md-6">
	                <div class="input-wrap">
	                   <label for="name" class="required"><?php echo __('Attachment')?></label>
	                    <div class="input-box">
	                        <input name="attachment" id="attachment" title="Attachment" class="input-text required-entry" type="file" data-validate="{required:true}">
	                    </div>
	                </div>
	            </div>
            </div>

        </div>
    </div>
    <!-- <div class="buttons-set"> -->
        <!-- <p class="required">* Required Fields</p> -->
        <!-- <input type="text" name="hideit" id="hideit" value="" style="display:none !important;"> -->

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="Submit" class="action primary"><span>Submit</span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="http://delami.executive.me/productreturn/action/"><span>Go back</span></a>
            </div>
        </div>
    <!-- </div> -->
</form>