<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php 
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $product = $objectManager->get('Magento\Catalog\Model\Product')->load($_product->getId());
                    $_tag = $product->getAttributeText('tag');
                    $specialprice = $_product->getSpecialPrice();
                    $specialPriceFromDate = $_product->getSpecialFromDate();
                    $specialPriceToDate = $_product->getSpecialToDate();    
                    $newsFrom = $_product->getNewsFromDate();
                    $newsTo = $_product->getNewsToDate();
                    $today = time();
                    $price = $_product->getPrice();
                    if($price){
                        $sale = round((($price-$specialprice)/$price)*100);
                    } else {
                        $sale = '';
                    }
                    
                    
                    //potongandiskon
                    if($_product->getTypeId() == "simple") {
                       $simplePrice = $_product->getPrice();
                    } else {
                       $_children = $_product->getTypeInstance()->getUsedProducts($_product);
                        foreach ($_children as $child){
                        $simplePrice = $child->getPrice();
                        break;
                       }
                    }

                    $_finalPrice = $_product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                    $_price = $simplePrice;
                    if($_finalPrice < $_price) {
                       $_savingPercent = 100 - round(($_finalPrice / $_price)*100);
                    }
                ?>


                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item-list col-md-3 col-xs-6 on-four">' : '</li><li class="item product product-item-list col-md-3 col-xs-6 on-four">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <div class="badges badges-top">
                        <?php if ($today >= strtotime($newsFrom) && $today <= strtotime($newsTo)) :?>
                            <div class="is-new">
                                <span>
                                    <?php echo __('NEW')?>
                                </span>
                            </div>
                        <?php endif ?>

                        <?php if ($_finalPrice < $_price): ?>
                            <div class="is-sale1">
                                <span>
                                    <?php if($_savingPercent) { echo $_savingPercent.'%'; } else {echo __('Sale');} ?>
                                </span>
                            </div>
                        <?php endif ?>
                    </div>

                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>

                    <div class="product details product-item-details">
                    
                        <?php if($_tag):?>
                            <div class="badges badges-bottom">
                                <div class="custom">
                                    <span>
                                        <?php echo $_tag ?>
                                    </span>
                                </div>
                            </div>
                        <?php endif ?>

                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        
                        <?php 
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
                        $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
                        $price =  $_product->getMaxPrice();
                        $configurableSale = $priceHelper->currency($price, true, false);
                        ?>

                        

                        <?= $block->getProductDetailsHtml($_product) ?>

                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require([ 'jquery'], function($){
       
       $('.view-mode-count a').each(function(){
            var product = $('.item.product');
            $(this).click(function() {
                $(this).siblings('a').removeClass('active');
                $(this).addClass('active');
                if ($(this).hasClass('view-four')){
                    product.removeClass('col-md-6');
                    product.addClass('col-md-3 on-four')
                }else{
                    product.removeClass('col-md-3 on-four');
                    product.addClass('col-md-6');
                }
                return false
            });
       });
       
    });
</script>